languageCode = "en-us"
theme = "PaperMod"
title = "Pd - Tip of the Day"
description = "things you should know about Pure Data"
[Params]
  author = "Pd community" # add your company name
  github = "pd-externals" # add your github profile name
  #twitter = "" # add your twitter profile
  #email = "zmoelnig@iem.at"
  #download = "https://iem.at/"
  disableSpecial1stPost = true

[[Params.socialIcons]]
  name = "github"
  url = "https://github.com/pd-externals/tipoftheday-plugin/"

[[menu.main]]
    name = "Add new Tip"
    weight = -200
    url = "https://github.com/pd-externals/tipoftheday-plugin/issues/new/choose"

[[menu.main]]
    name = "Legal"
    weight = 999
    url = "/legal/"
